#!/bin/sh

echo ""
echo "Updating.."
sudo apt update -y 

echo ""
echo "Upgrading.."
sudo apt upgrade -y 

echo ""
echo "Cleaning.."
sudo apt autoclean -y

echo ""
echo "Removing.."
sudo apt autoremove -y

echo ""
echo "Cleaning again.."
sudo apt clean -y

echo "Shutdown Complete. Goodbye!"
sudo shutdown now
